baseurl = "https://devsecops-workshop.github.io/"
contentdir    = "content"
layoutdir     = "layouts"
publishdir    = "public"
title = "Camel K Workshop"
canonifyurls = true
paginate = 10

# Change the default theme to be use when building the site with Hugo
theme = "hugo-theme-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[author]
  name = "Rui, Tala, Fabian, Adrian"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "A Camel K Workshop using OpenShift"
  Author = "Rui, Tala, Fabian, Adrian"
  Ganalytics = "XX-00000000-0"
  themeVariant = "red"
  disableInlineCopyToClipBoard = "false"

## Use those parameters with {{< param "param_name" >}}
  deployment = "production"

[[menu.shortcuts]]
name = "<i class='fas fa-home'></i> Homepage"
url = "https://devsecops-workshop.github.io/"
weight = 10

[markup]
#defaultMarkdownHandler = "blackfriday"
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
